spring:
  application:
    name: bcafly-backend
  profiles:
    active: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/bcafly_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "hizor"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  jwt:
    secret: BcaFlySecretKey2026ChangeThisInProduction
    expiration-ms: 86400000  # 24 hours
  storage:
    upload-dir: ../storage/uploads
    report-dir: ../storage/reports
    export-dir: ../storage/exports
    backup-dir: ../storage/backups
